console.log('hello javascript');
console.log('hai Gilang, Semangat belajar JavaScript yaa');
console.log(process.memoryUsage());
console.log('hello javascript');
console.log('hai Gilang, Semangat belajar JavaScript yaa');
console.log(process.memoryUsage());
console.log('hello javascript');
console.log('hai Gilang, Semangat belajar JavaScript yaa');
console.log(process.memoryUsage());
console.log('hello javascript');
console.log('hai Gilang, Semangat belajar JavaScript yaa');
console.log(process.memoryUsage());
console.log('hello javascript');
console.log('hai Gilang, Semangat belajar JavaScript yaa');
console.log(process.memoryUsage());